from typing import Any


class PyAttribute:
    @property
    def value(self): ...
    @property
    def initial(self): ...

    def set_value(self, value, epoch: int): ...


class PyEntityIdentifier:
    def has_applied_pk(self) -> bool: ...
    def get_uuid(self) -> str: ...
    def get_model(self) -> str: ...
    def get_applied_pk(self) -> int: ...


class PyEntity:

    def get(self, attr_name: str) -> PyAttribute:...

class PyEntityStore:
    def    get( self, identifier: PyEntityIdentifier) -> PyEntity: ...
    def    filter( self, model: str, **kwargs) -> list[PyEntity]: ...
    def    instantiate_entity(self, identifier: PyEntityIdentifier) -> PyEntity: ...


def create_database_value(t: str) -> Any: ...
def repr_database_value(t: Any) -> str: ...